#!/bin/bash
   
while true;
 do 

  echo
  echo 
  echo starting $(date);

  script_directory=`dirname "$0"`;
  cd $script_directory;
  
  #node app.js $* > log/nodejs.log 2>&1;
  node app.js $*;

  exit_value="$?" ;
  echo stopping $(date);
   
  if [ "$exit_value" != "0" ]; then 
   sleep 5;
  else 
   sleep 0.5;
  fi ;

 done;
